version: '3'

services:

  sol:
    build: .
    entrypoint: "npm run start"

    environment:
      - DOCKER_HOST=sol

  testcafe:
    image: testcafe/testcafe:latest
    volumes:
      - /Users/johan/Development/sol_nuxt/e2e:/tests
    entrypoint: /opt/testcafe/docker/testcafe-docker.sh 'chromium:headless --no-sandbox' /tests/tests.js
    environment:
      - TEST_SERVER=sol
    depends_on:
      - sol

