version: '3'

services:

  sol:
    build: .
    entrypoint: "npm run start"

    environment:
      - DOCKER_HOST=sol
      # - BASE_URL="/oversattarlexikon/"
    # ports:
    #   - 3000:3000

  testcafe:
    image: testcafe/testcafe@sha256:1cf8eae0d73b2070ff3f8069c2baeab4d9f0c985aab81c00ea8f38d293dadf0f
    volumes:
      - ./e2e:/tests
    entrypoint: /opt/testcafe/docker/testcafe-docker.sh 'chromium:headless --no-sandbox' /tests/tests.js
    environment:
      - TEST_SERVER=sol
    depends_on:
      - sol

