version: '3'

services:

  sol:
    build: .
    entrypoint: "npm run start"

    environment:
      - DOCKER_HOST=sol
      - BASE_URL=/%C3%B6vers%C3%A4ttarlexikon/
    ports:
      - 3000:3000

  testcafe:
    image: testcafe/testcafe
    volumes:
      - ./e2e:/tests
    entrypoint: /opt/testcafe/docker/testcafe-docker.sh 'chromium:headless --no-sandbox' /tests/tests.js
    environment:
      - TEST_SERVER=sol
      - BASE_URL=/%C3%B6vers%C3%A4ttarlexikon/
    depends_on:
      - sol

